#!/usr/bin/env sh
# for this to work you must configure sudo such that
# it will be able to run the command without password

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# sudo yabai --load-sa
#
#yabai -m space 1 --label "Chat"
#yabai -m space 2 --label "Browser"
#yabai -m space 3 --label "Code"
#yabai -m space 4 --label "Misc"


# yabai -m rule --add app="^Discord$" space="Chat"
# yabai -m rule --add app="^Telegram$" space="Chat"


# global settings
yabai -m config                                 \
    mouse_follows_focus          on             \
    focus_follows_mouse          autoraise      \
    window_origin_display        default        \
    window_placement             second_child   \
    window_zoom_persist          on             \
    window_topmost               off             \
    window_shadow                float          \
    window_animation_duration    0.0            \
    window_animation_frame_rate  120            \
    window_opacity_duration      0.0            \
    active_window_opacity        1.00            \
    normal_window_opacity        0.90           \
    window_opacity               on             \
    insert_feedback_color        0xffd75f5f     \
    active_window_border_color   0xff775759     \
    normal_window_border_color   0xff555555     \
    window_border_width          4              \
    window_border_radius         4             \
    window_border_blur           off             \
    window_border_hidpi          off             \
    window_border                off             \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  44             \
    bottom_padding               12             \
    left_padding                 12             \
    right_padding                12             \
    window_gap                   20             \
    layout                       bsp            \
    mouse_modifier               fn             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap

echo "yabai configuration loaded.."

yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add title=' Preferences$' manage=off
#yabai -m rule --add title='^Telegram$' manage=off

